### ISSUE TITLE
Questions about slumba

### ISSUE THREAD

**Issue by nelson2005** [cpcloud/slumba#2]
Hello- this is really impressive work.  I don't have anything near your level of expertise on numba, but I was trying to bring this up to date with numba 0.50.0 and ran into an issue, so have a few questions.

1. what version of numba did this work with (if you remember)
2. I tried the scalar udf in the README, like
```python
@sqlite_udf(int64(int64))
def add_one(x):
    if x is not None:
        return x + 1
    return None
```
and received a compile error like
> numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
> No conversion from none to int64 for '$20return_value.1', defined at None

at

```python
compiled_func = njit(signature, nogil=nogil, **njit_kwargs)(func)
```
in scalar.py.  A standalone @njit of the same function produces the same error, so I think it's happening in numba.  I can post more details somewhere if it would help.
3. Has anyone that you know of taken your work forward?  I saw a presentation you did on it a couple of years ago, but was surprised at the lack of hits on google.  This work seems significant enough that I would have expected more attention on the net.

Thanks

Erik

**Comment by nelson2005** [comment]
after reviewing the notebook, I solved #2 with optional(), like

```python
@sqlite_udf(optional(int64)(optional(int64)))
def add_one(x):
    if x is not None:
        return x + 1
    return None
```

so pay that one no mind

**Comment by cpcloud** [comment]
@nelson2005 Thanks for the kind words. This was a fun project to create and a great learning experience for me that revealed the raw, user-facing power of numba.

> what version of numba did this work with (if you remember)

I don't remember :(

However, I have recently updated the package to work with 0.53.1, but I haven't yet cut a release.

I am currently working on setting a fully automated release pipeline using GitHub actions and semantic release tooling, that will release to PyPI on every commit per [semantic release](https://github.com/semantic-release/semantic-release#how-does-it-work).

> I tried the scalar udf in the README,

Thanks for pointing this out. It looks like I need to clarify that use of `None`-as-`NULL` requires the use of the `optional` construct.

> Has anyone that you know of taken your work forward?

Not that I am aware of. There are a couple of things to do depending on interest:

1. Propose a patch to CPython to add the ability for aggregates to support window functions similar to the API I wrote in slumba. This would basically be extending the API to support optional `inverse` and `value` methods. This isn't direct use of the library, but could be an example implementation of such an API.
2. The library could probably use a security review, since it's passing around raw pointers as integers and then casting them to function pointers which are called by a third party library. Needless to say, it's very unsafe to call functions in this way, function pointer clobbering being a possible attack vector (and probably other pointer subterfuge is possible).

**Comment by nelson2005** [comment]
I feel like I got it pretty much working without the C shim.... Since we can get the address on the [python side](https://numba.discourse.group/t/signature-inspection-with-jitclass/210) and cast it freely, we can effectively use cffi (I used the pypy definitions) and access the C API directly. What makes the shim necessary?

Also, fwiw, jitclass was the only way to go back when I started this, but now it appears that structref is the future and better.  The struct is allocated on the 'C' side and you write jotted function accessors.  I've since converted my core classes to structref but haven't yet gotten time to get the SQLite bits in order.

**Comment by cpcloud** [comment]
@nelson2005 Neat. The (now C++) shim is necessary to get the address of the raw `sqlite3*` database to pass around (it's used in a few places). I would love to get rid of that entirely. It sounds like you've been able to do that; would you be able to point me to some code or make a PR?

Re: `structref`, I wasn't aware of that, but I'll take a look. I'm also starting to investigate string support, since numba seems to have grown a decent number of string functions since the last time I looked.

**Comment by nelson2005** [comment]
There are a few variations, but I used the key observation (maybe from @rogerbinns of APSW fame, I don't remember exactly as it was some time ago) that the sqlite db pointer would be immediately after the pyobject bit of the python handle, like below.  There are a few different ways to get at it, but basically if you can just get the right offset from the python object you can get the pointer and then cast it about as you wish.

Also, fwiw, numba does have a voidp type so I was largely able to avoid converting the pointer to integer unless it had to pass though 'plain python' code.  I think with the memory layouts in numba even such things as zero-copy virtual tables that expose numpy ndarrays though a numba/sqlite virtual table interface is possible.  I did several proof of concepts that worked quite well prior to other things taking precedence.  If I were doing it again I'd start from scratch with the sqlite cffi headers from pypi and structrefs from numba.

python```
def get_db_from_connection_noffi(connection):
    if hasattr(ctypes.pythonapi, "Py_InitModule4_64"):
        _Py_ssize_t = ctypes.c_int64
    else:
        _Py_ssize_t = ctypes.c_int

    class _Connection(ctypes.Structure):
        _fields_ = [
            ("ob_refcnt", _Py_ssize_t),
            ("ob_type", ctypes.c_void_p),
            ("db", ctypes.c_void_p),
        ]

    assert isinstance(connection, sqlite3.Connection)
    return _Connection.from_address(id(connection)).db
```

**Comment by cpcloud** [comment]
@nelson2005 Thanks, I've merged https://github.com/cpcloud/slumba/pull/3 into master and a (platform independent) release should be out as soon as the build publishes it to PyPI.

**Comment by nelson2005** [comment]
Awesome, I'm looking forward to the virtual table support! :)
